#端口
server:
  port: 8001
# 数据库连接信息
spring:
  datasource:
           url: jdbc:mysql://sc.vip.com:3306/simons?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
           username: root
           password: root
           driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-provider

# mybatis扫描信息
mybatis:
  typeAliasesPackage: com.simons.cn.bean       #实体对象所以在包
  mapper-locations: classpath:mapper/*.xml       #xml文件位置

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/    #如果Eureka是集群，这里则配置多个，例如 defaultZone: http://localhost:8500/eureka/,http://localhost:8501/eureka/
  instance:
     prefer-ip-address: true
